---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-elbv2-controller.app.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-elbv2-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-elbv2-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-elbv2-controller.chart.name-version" . }}
rules:
- apiGroups:
  - elbv2.services.k8s.aws
  resources:
  - listeners
  - loadbalancers
  - rules
  - targetgroups
  verbs:
  - get
  - list
  - watch
