// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package target_group

import (
	"context"
	"fmt"
	"time"

	svcapitypes "github.com/aws-controllers-k8s/elbv2-controller/apis/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2/types"
)

var (
	RequeueAfterUpdateDuration = 5 * time.Second
)

func customCompare(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	compareTargetDescription(delta, a, b)
	compareTargetGroupAttributes(delta, a, b)
}

// compareTargetGroupAttributes compares the attributes of the target group.
// Since Attributes is marked as compare.is_ignored in generator.yaml, ACK
// will not automatically compare them. This function performs the comparison
// and adds a delta entry if the attributes have changed.
func compareTargetGroupAttributes(
	delta *ackcompare.Delta,
	a *resource,
	b *resource,
) {
	if targetGroupAttributesHaveChanged(a.ko.Spec.Attributes, b.ko.Spec.Attributes) {
		delta.Add("Spec.Attributes", a.ko.Spec.Attributes, b.ko.Spec.Attributes)
	}
}

// targetGroupAttributesHaveChanged returns true if the desired attributes (a) differ
// from the latest attributes (b). It performs a bidirectional comparison:
// - Checks if any desired attribute is missing or has a different value in latest
// - Checks if any latest attribute is missing from desired (i.e., attribute was removed)
//
// When the desired set is empty, no change is reported. This is intentional:
// removing some attributes resets them, but an entirely empty desired set means
// the user has not opted into attribute management — we leave server-side
// defaults untouched. Without this guard, the controller would loop: reset
// attributes → AWS returns defaults → detect change → reset again.
func targetGroupAttributesHaveChanged(a, b []*svcapitypes.TargetGroupAttribute) bool {
	if len(a) == 0 {
		return false
	}
	// Check if any desired attribute is missing or different in latest
	for _, attrA := range a {
		if !containsExactTargetGroupAttribute(b, attrA) {
			return true
		}
	}
	// Check if any latest attribute is missing from desired (attribute removal)
	for _, attrB := range b {
		if !containsExactTargetGroupAttribute(a, attrB) {
			return true
		}
	}
	return false
}

// containsExactTargetGroupAttribute returns true if the key is in the attributes slice
// and has the same value. Nil-value attributes with the same key are considered equal.
func containsExactTargetGroupAttribute(attributes []*svcapitypes.TargetGroupAttribute, targetAttribute *svcapitypes.TargetGroupAttribute) bool {
	for _, attribute := range attributes {
		if attribute.Key != nil && targetAttribute.Key != nil &&
			*attribute.Key == *targetAttribute.Key &&
			((attribute.Value == nil && targetAttribute.Value == nil) ||
				(attribute.Value != nil && targetAttribute.Value != nil &&
					*attribute.Value == *targetAttribute.Value)) {
			return true
		}
	}
	return false
}

// getTargetGroupAttributes returns the attributes of the target group from AWS.
func (rm *resourceManager) getTargetGroupAttributes(
	ctx context.Context,
	ko *svcapitypes.TargetGroup,
) ([]*svcapitypes.TargetGroupAttribute, error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.getTargetGroupAttributes")
	var err error
	defer func() {
		exit(err)
	}()

	attributes := []*svcapitypes.TargetGroupAttribute{}
	var resp *svcsdk.DescribeTargetGroupAttributesOutput

	if ko.Status.ACKResourceMetadata == nil || ko.Status.ACKResourceMetadata.ARN == nil {
		return nil, fmt.Errorf("target group ARN is not yet available")
	}
	resp, err = rm.sdkapi.DescribeTargetGroupAttributes(ctx, &svcsdk.DescribeTargetGroupAttributesInput{
		TargetGroupArn: (*string)(ko.Status.ACKResourceMetadata.ARN),
	})
	rm.metrics.RecordAPICall("READ_ONE", "DescribeTargetGroupAttributes", err)
	if err != nil {
		return nil, err
	}

	// Convert the attributes SDK type to the k8s API type
	for _, attr := range resp.Attributes {
		attribute := &svcapitypes.TargetGroupAttribute{
			Key:   attr.Key,
			Value: attr.Value,
		}
		attributes = append(attributes, attribute)
	}
	return attributes, nil
}

// customBuildAttributesForUpdate builds the complete set of TargetGroupAttribute
// to send in a ModifyTargetGroupAttributes API call. It merges:
//   - Desired attributes from the user spec (key → value)
//   - Reset entries for attributes that exist in latest but are NOT in desired
//     (key → "") to return them to their AWS defaults
//
// This is a pure function, separated from updateTargetGroupAttributes so it can
// be unit-tested without mocking the AWS SDK or resource manager.
func customBuildAttributesForUpdate(
	desired []*svcapitypes.TargetGroupAttribute,
	latest []*svcapitypes.TargetGroupAttribute,
) []svcsdktypes.TargetGroupAttribute {
	desiredAttrs := make(map[string]string)
	for _, attr := range desired {
		if attr.Key == nil || *attr.Key == "" {
			continue
		}
		if attr.Value != nil {
			desiredAttrs[*attr.Key] = *attr.Value
		} else {
			desiredAttrs[*attr.Key] = ""
		}
	}

	sdkAttributes := []svcsdktypes.TargetGroupAttribute{}
	for key, value := range desiredAttrs {
		sdkAttributes = append(sdkAttributes, svcsdktypes.TargetGroupAttribute{
			Key:   &key,
			Value: &value,
		})
	}
	for _, attr := range latest {
		if attr.Key == nil || *attr.Key == "" {
			continue
		}
		if _, exists := desiredAttrs[*attr.Key]; !exists {
			emptyVal := ""
			sdkAttributes = append(sdkAttributes, svcsdktypes.TargetGroupAttribute{
				Key:   attr.Key,
				Value: &emptyVal,
			})
		}
	}
	return sdkAttributes
}

// updateTargetGroupAttributes updates the attributes of the target group.
// It computes the full set of attributes to send to AWS:
// - Desired attributes from the user spec are included with their values
// - Attributes that exist in latest but are NOT in desired are included with
//   an empty value to reset them to their default. Note: empty-string reset has
//   not been verified against all attribute types. Enum attributes (e.g.
//   stickiness.type, load_balancing.algorithm.type) and numeric attributes may
//   reject an empty string. Test with your specific attribute set.
// - Attributes with nil/empty keys are skipped
func (rm *resourceManager) updateTargetGroupAttributes(
	ctx context.Context,
	desired *resource,
	latest *resource,
) error {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.updateTargetGroupAttributes")
	var err error
	defer func() {
		exit(err)
	}()

	sdkAttributes := customBuildAttributesForUpdate(desired.ko.Spec.Attributes, latest.ko.Spec.Attributes)
	if len(sdkAttributes) == 0 {
		return nil
	}

	if desired.ko.Status.ACKResourceMetadata == nil || desired.ko.Status.ACKResourceMetadata.ARN == nil {
		return fmt.Errorf("target group ARN is not yet available")
	}

	input := &svcsdk.ModifyTargetGroupAttributesInput{
		TargetGroupArn: (*string)(desired.ko.Status.ACKResourceMetadata.ARN),
		Attributes:     sdkAttributes,
	}
	_, err = rm.sdkapi.ModifyTargetGroupAttributes(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyTargetGroupAttributes", err)
	if err != nil {
		return err
	}

	return nil
}

func compareTargetDescription(
	delta *ackcompare.Delta,
	desired *resource,
	latest *resource,
) {
	if len(desired.ko.Spec.Targets) != len(latest.ko.Spec.Targets) {
		delta.Add("Spec.Targets", desired.ko.Spec.Targets, latest.ko.Spec.Targets)
	} else if len(desired.ko.Spec.Targets) > 0 {
		added, removed := getTargetsDifference(latest.ko.Spec.Targets, desired.ko.Spec.Targets)

		if len(added) > 0 || len(removed) > 0 {
			delta.Add("Spec.Targets", added, removed)
		}
		return

	}
}

func areDifferentTarget(latest, desired *svcapitypes.TargetDescription) bool {
	if (latest == nil && desired != nil) || (latest != nil && desired == nil) {
		return true
	}

	if latest.Port != nil && desired.Port == nil {
		desired.Port = latest.Port
	}
	if latest.AvailabilityZone != nil && desired.AvailabilityZone == nil {
		desired.AvailabilityZone = latest.AvailabilityZone
	}
	if (latest.ID == nil && desired.ID != nil) || (latest.ID != nil && desired.ID == nil) ||
		(latest.ID != nil && desired.ID != nil && *latest.ID != *desired.ID) ||
		(latest.Port == nil && desired.Port != nil) || (latest.Port != nil && desired.Port != nil && *latest.Port != *desired.Port) ||
		(latest.AvailabilityZone == nil && desired.AvailabilityZone != nil) ||
		(latest.AvailabilityZone != nil && desired.AvailabilityZone != nil && *latest.AvailabilityZone != *desired.AvailabilityZone) {
		return true
	}

	return false
}

func getTargetsDifference(
	latest []*svcapitypes.TargetDescription,
	desired []*svcapitypes.TargetDescription,
) (added []*svcapitypes.TargetDescription, removed []*svcapitypes.TargetDescription) {

	toAdd := make([]*svcapitypes.TargetDescription, 0, min(len(latest), len(desired)))
	toDelete := make([]*svcapitypes.TargetDescription, 0, min(len(latest), len(desired)))

	am := make(map[string]*svcapitypes.TargetDescription)

	for _, v := range latest {
		am[*v.ID] = v
	}

	for _, v := range desired {
		if t, ok := am[*v.ID]; !ok || areDifferentTarget(t, v) {
			toAdd = append(toAdd, v)
		}
	}

	bm := make(map[string]*svcapitypes.TargetDescription)
	for _, v := range desired {
		bm[*v.ID] = v
	}

	for _, v := range latest {
		if _, ok := bm[*v.ID]; !ok {
			toDelete = append(toDelete, v)
		}
	}

	return toAdd, toDelete
}

func (rm *resourceManager) registerTargets(
	ctx context.Context,
	arn string,
	targets []*svcapitypes.TargetDescription,
) (err error) {

	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.registerTargets")
	defer func() { exit(err) }()

	input := &svcsdk.RegisterTargetsInput{
		TargetGroupArn: &arn,
		Targets:        apifyTargetDescription(targets),
	}
	_, err = rm.sdkapi.RegisterTargets(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "RegisterTargets", err)
	if err != nil {
		return err
	}

	return nil
}

func (rm *resourceManager) deregisterTargets(
	ctx context.Context,
	arn string,
	targets []*svcapitypes.TargetDescription,
) (err error) {
	if len(targets) == 0 {
		return nil
	}

	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.deregisterTargets")
	defer func() { exit(err) }()

	input := &svcsdk.DeregisterTargetsInput{
		TargetGroupArn: &arn,
		Targets:        apifyTargetDescription(targets),
	}
	_, err = rm.sdkapi.DeregisterTargets(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "DeregisterTargets", err)
	if err != nil {
		return err
	}

	return nil
}

func (rm *resourceManager) describeTargets(
	ctx context.Context,
	res *resource,
) (err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.describeTargets")
	defer func() { exit(err) }()

	input := &svcsdk.DescribeTargetHealthInput{
		TargetGroupArn: (*string)(res.ko.Status.ACKResourceMetadata.ARN),
	}
	resp, err := rm.sdkapi.DescribeTargetHealth(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeTargetHealth", err)
	if err != nil {
		return err
	}

	targetHealthPtrs := make([]*svcsdktypes.TargetHealthDescription, len(resp.TargetHealthDescriptions))
	for i := range resp.TargetHealthDescriptions {
		targetHealthPtrs[i] = &resp.TargetHealthDescriptions[i]
	}
	res.ko.Spec.Targets = extractTargetDescription(targetHealthPtrs)
	return nil
}

func apifyTargetDescription(target []*svcapitypes.TargetDescription) []svcsdktypes.TargetDescription {
	convertedTarget := make([]svcsdktypes.TargetDescription, len(target))
	for i, t := range target {
		td := svcsdktypes.TargetDescription{
			Id:               t.ID,
			AvailabilityZone: t.AvailabilityZone,
		}
		if t.Port != nil {
			td.Port = aws.Int32(int32(*t.Port))
		}
		convertedTarget[i] = td
	}
	return convertedTarget
}

func extractTargetDescription(targetHealth []*svcsdktypes.TargetHealthDescription) []*svcapitypes.TargetDescription {
	convertedTarget := make([]*svcapitypes.TargetDescription, 0, len(targetHealth))
	for _, t := range targetHealth {
		if t.Target == nil {
			continue
		}
		td := &svcapitypes.TargetDescription{
			ID:               t.Target.Id,
			AvailabilityZone: t.Target.AvailabilityZone,
		}
		if t.Target.Port != nil {
			td.Port = aws.Int64(int64(*t.Target.Port))
		}
		convertedTarget = append(convertedTarget, td)
	}
	return convertedTarget
}
