// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package listener

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/elbv2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elbv2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.ELBV2{}
	_ = &svcapitypes.Listener{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// The ARN is guaranteed to be checked by the sdkFind method. We can safely cast it here.
	input.SetListenerArns([]*string{(*string)(r.ko.Status.ACKResourceMetadata.ARN)})
	// Unset the LoadBalancerArn field since we can't set both ListenerArn and LoadBalancerArn
	// Probably needs to be done in the code-generator. @a-hilaly.
	input.LoadBalancerArn = nil
	var resp *svcsdk.DescribeListenersOutput
	resp, err = rm.sdkapi.DescribeListenersWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeListeners", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "ListenerNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			f0 := []*string{}
			for _, f0iter := range elem.AlpnPolicy {
				var f0elem string
				f0elem = *f0iter
				f0 = append(f0, &f0elem)
			}
			ko.Spec.AlpnPolicy = f0
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0f0 := map[string]*string{}
						for f2elemf0f0key, f2elemf0f0valiter := range f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams {
							var f2elemf0f0val string
							f2elemf0f0val = *f2elemf0f0valiter
							f2elemf0f0[f2elemf0f0key] = &f2elemf0f0val
						}
						f2elemf0.AuthenticationRequestExtraParams = f2elemf0f0
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
						f2elemf0.OnUnauthenticatedRequest = f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1f0 := map[string]*string{}
						for f2elemf1f0key, f2elemf1f0valiter := range f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams {
							var f2elemf1f0val string
							f2elemf1f0val = *f2elemf1f0valiter
							f2elemf1f0[f2elemf1f0key] = &f2elemf1f0val
						}
						f2elemf1.AuthenticationRequestExtraParams = f2elemf1f0
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != nil {
						f2elemf1.OnUnauthenticatedRequest = f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							f2elemf3f0.DurationSeconds = f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								f2elemf3f1elem.Weight = f2elemf3f1iter.Weight
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					f2elem.Order = f2iter.Order
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != nil {
						f2elemf5.StatusCode = f2iter.RedirectConfig.StatusCode
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != nil {
					f2elem.Type = f2iter.Type
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			ko.Spec.Port = elem.Port
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != nil {
			ko.Spec.Protocol = elem.Protocol
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return rm.customCheckRequiredFieldsMissingMethod(r)
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeListenersInput, error) {
	res := &svcsdk.DescribeListenersInput{}

	if r.ko.Spec.LoadBalancerARN != nil {
		res.SetLoadBalancerArn(*r.ko.Spec.LoadBalancerARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateListenerOutput
	_ = resp
	resp, err = rm.sdkapi.CreateListenerWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateListener", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			f0 := []*string{}
			for _, f0iter := range elem.AlpnPolicy {
				var f0elem string
				f0elem = *f0iter
				f0 = append(f0, &f0elem)
			}
			ko.Spec.AlpnPolicy = f0
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0f0 := map[string]*string{}
						for f2elemf0f0key, f2elemf0f0valiter := range f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams {
							var f2elemf0f0val string
							f2elemf0f0val = *f2elemf0f0valiter
							f2elemf0f0[f2elemf0f0key] = &f2elemf0f0val
						}
						f2elemf0.AuthenticationRequestExtraParams = f2elemf0f0
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
						f2elemf0.OnUnauthenticatedRequest = f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1f0 := map[string]*string{}
						for f2elemf1f0key, f2elemf1f0valiter := range f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams {
							var f2elemf1f0val string
							f2elemf1f0val = *f2elemf1f0valiter
							f2elemf1f0[f2elemf1f0key] = &f2elemf1f0val
						}
						f2elemf1.AuthenticationRequestExtraParams = f2elemf1f0
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != nil {
						f2elemf1.OnUnauthenticatedRequest = f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							f2elemf3f0.DurationSeconds = f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								f2elemf3f1elem.Weight = f2elemf3f1iter.Weight
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					f2elem.Order = f2iter.Order
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != nil {
						f2elemf5.StatusCode = f2iter.RedirectConfig.StatusCode
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != nil {
					f2elem.Type = f2iter.Type
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			ko.Spec.Port = elem.Port
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != nil {
			ko.Spec.Protocol = elem.Protocol
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateListenerInput, error) {
	res := &svcsdk.CreateListenerInput{}

	if r.ko.Spec.AlpnPolicy != nil {
		f0 := []*string{}
		for _, f0iter := range r.ko.Spec.AlpnPolicy {
			var f0elem string
			f0elem = *f0iter
			f0 = append(f0, &f0elem)
		}
		res.SetAlpnPolicy(f0)
	}
	if r.ko.Spec.Certificates != nil {
		f1 := []*svcsdk.Certificate{}
		for _, f1iter := range r.ko.Spec.Certificates {
			f1elem := &svcsdk.Certificate{}
			if f1iter.CertificateARN != nil {
				f1elem.SetCertificateArn(*f1iter.CertificateARN)
			}
			if f1iter.IsDefault != nil {
				f1elem.SetIsDefault(*f1iter.IsDefault)
			}
			f1 = append(f1, f1elem)
		}
		res.SetCertificates(f1)
	}
	if r.ko.Spec.DefaultActions != nil {
		f2 := []*svcsdk.Action{}
		for _, f2iter := range r.ko.Spec.DefaultActions {
			f2elem := &svcsdk.Action{}
			if f2iter.AuthenticateCognitoConfig != nil {
				f2elemf0 := &svcsdk.AuthenticateCognitoActionConfig{}
				if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
					f2elemf0f0 := map[string]*string{}
					for f2elemf0f0key, f2elemf0f0valiter := range f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams {
						var f2elemf0f0val string
						f2elemf0f0val = *f2elemf0f0valiter
						f2elemf0f0[f2elemf0f0key] = &f2elemf0f0val
					}
					f2elemf0.SetAuthenticationRequestExtraParams(f2elemf0f0)
				}
				if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
					f2elemf0.SetOnUnauthenticatedRequest(*f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateCognitoConfig.Scope != nil {
					f2elemf0.SetScope(*f2iter.AuthenticateCognitoConfig.Scope)
				}
				if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
					f2elemf0.SetSessionCookieName(*f2iter.AuthenticateCognitoConfig.SessionCookieName)
				}
				if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
					f2elemf0.SetSessionTimeout(*f2iter.AuthenticateCognitoConfig.SessionTimeout)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolARN != nil {
					f2elemf0.SetUserPoolArn(*f2iter.AuthenticateCognitoConfig.UserPoolARN)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolClientID != nil {
					f2elemf0.SetUserPoolClientId(*f2iter.AuthenticateCognitoConfig.UserPoolClientID)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
					f2elemf0.SetUserPoolDomain(*f2iter.AuthenticateCognitoConfig.UserPoolDomain)
				}
				f2elem.SetAuthenticateCognitoConfig(f2elemf0)
			}
			if f2iter.AuthenticateOIDCConfig != nil {
				f2elemf1 := &svcsdk.AuthenticateOidcActionConfig{}
				if f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams != nil {
					f2elemf1f0 := map[string]*string{}
					for f2elemf1f0key, f2elemf1f0valiter := range f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams {
						var f2elemf1f0val string
						f2elemf1f0val = *f2elemf1f0valiter
						f2elemf1f0[f2elemf1f0key] = &f2elemf1f0val
					}
					f2elemf1.SetAuthenticationRequestExtraParams(f2elemf1f0)
				}
				if f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint != nil {
					f2elemf1.SetAuthorizationEndpoint(*f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint)
				}
				if f2iter.AuthenticateOIDCConfig.ClientID != nil {
					f2elemf1.SetClientId(*f2iter.AuthenticateOIDCConfig.ClientID)
				}
				if f2iter.AuthenticateOIDCConfig.ClientSecret != nil {
					f2elemf1.SetClientSecret(*f2iter.AuthenticateOIDCConfig.ClientSecret)
				}
				if f2iter.AuthenticateOIDCConfig.Issuer != nil {
					f2elemf1.SetIssuer(*f2iter.AuthenticateOIDCConfig.Issuer)
				}
				if f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest != nil {
					f2elemf1.SetOnUnauthenticatedRequest(*f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateOIDCConfig.Scope != nil {
					f2elemf1.SetScope(*f2iter.AuthenticateOIDCConfig.Scope)
				}
				if f2iter.AuthenticateOIDCConfig.SessionCookieName != nil {
					f2elemf1.SetSessionCookieName(*f2iter.AuthenticateOIDCConfig.SessionCookieName)
				}
				if f2iter.AuthenticateOIDCConfig.SessionTimeout != nil {
					f2elemf1.SetSessionTimeout(*f2iter.AuthenticateOIDCConfig.SessionTimeout)
				}
				if f2iter.AuthenticateOIDCConfig.TokenEndpoint != nil {
					f2elemf1.SetTokenEndpoint(*f2iter.AuthenticateOIDCConfig.TokenEndpoint)
				}
				if f2iter.AuthenticateOIDCConfig.UseExistingClientSecret != nil {
					f2elemf1.SetUseExistingClientSecret(*f2iter.AuthenticateOIDCConfig.UseExistingClientSecret)
				}
				if f2iter.AuthenticateOIDCConfig.UserInfoEndpoint != nil {
					f2elemf1.SetUserInfoEndpoint(*f2iter.AuthenticateOIDCConfig.UserInfoEndpoint)
				}
				f2elem.SetAuthenticateOidcConfig(f2elemf1)
			}
			if f2iter.FixedResponseConfig != nil {
				f2elemf2 := &svcsdk.FixedResponseActionConfig{}
				if f2iter.FixedResponseConfig.ContentType != nil {
					f2elemf2.SetContentType(*f2iter.FixedResponseConfig.ContentType)
				}
				if f2iter.FixedResponseConfig.MessageBody != nil {
					f2elemf2.SetMessageBody(*f2iter.FixedResponseConfig.MessageBody)
				}
				if f2iter.FixedResponseConfig.StatusCode != nil {
					f2elemf2.SetStatusCode(*f2iter.FixedResponseConfig.StatusCode)
				}
				f2elem.SetFixedResponseConfig(f2elemf2)
			}
			if f2iter.ForwardConfig != nil {
				f2elemf3 := &svcsdk.ForwardActionConfig{}
				if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
					f2elemf3f0 := &svcsdk.TargetGroupStickinessConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
						f2elemf3f0.SetDurationSeconds(*f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds)
					}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
						f2elemf3f0.SetEnabled(*f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled)
					}
					f2elemf3.SetTargetGroupStickinessConfig(f2elemf3f0)
				}
				if f2iter.ForwardConfig.TargetGroups != nil {
					f2elemf3f1 := []*svcsdk.TargetGroupTuple{}
					for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
						f2elemf3f1elem := &svcsdk.TargetGroupTuple{}
						if f2elemf3f1iter.TargetGroupARN != nil {
							f2elemf3f1elem.SetTargetGroupArn(*f2elemf3f1iter.TargetGroupARN)
						}
						if f2elemf3f1iter.Weight != nil {
							f2elemf3f1elem.SetWeight(*f2elemf3f1iter.Weight)
						}
						f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
					}
					f2elemf3.SetTargetGroups(f2elemf3f1)
				}
				f2elem.SetForwardConfig(f2elemf3)
			}
			if f2iter.Order != nil {
				f2elem.SetOrder(*f2iter.Order)
			}
			if f2iter.RedirectConfig != nil {
				f2elemf5 := &svcsdk.RedirectActionConfig{}
				if f2iter.RedirectConfig.Host != nil {
					f2elemf5.SetHost(*f2iter.RedirectConfig.Host)
				}
				if f2iter.RedirectConfig.Path != nil {
					f2elemf5.SetPath(*f2iter.RedirectConfig.Path)
				}
				if f2iter.RedirectConfig.Port != nil {
					f2elemf5.SetPort(*f2iter.RedirectConfig.Port)
				}
				if f2iter.RedirectConfig.Protocol != nil {
					f2elemf5.SetProtocol(*f2iter.RedirectConfig.Protocol)
				}
				if f2iter.RedirectConfig.Query != nil {
					f2elemf5.SetQuery(*f2iter.RedirectConfig.Query)
				}
				if f2iter.RedirectConfig.StatusCode != nil {
					f2elemf5.SetStatusCode(*f2iter.RedirectConfig.StatusCode)
				}
				f2elem.SetRedirectConfig(f2elemf5)
			}
			if f2iter.TargetGroupARN != nil {
				f2elem.SetTargetGroupArn(*f2iter.TargetGroupARN)
			}
			if f2iter.Type != nil {
				f2elem.SetType(*f2iter.Type)
			}
			f2 = append(f2, f2elem)
		}
		res.SetDefaultActions(f2)
	}
	if r.ko.Spec.LoadBalancerARN != nil {
		res.SetLoadBalancerArn(*r.ko.Spec.LoadBalancerARN)
	}
	if r.ko.Spec.MutualAuthentication != nil {
		f4 := &svcsdk.MutualAuthenticationAttributes{}
		if r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
			f4.SetIgnoreClientCertificateExpiry(*r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry)
		}
		if r.ko.Spec.MutualAuthentication.Mode != nil {
			f4.SetMode(*r.ko.Spec.MutualAuthentication.Mode)
		}
		if r.ko.Spec.MutualAuthentication.TrustStoreARN != nil {
			f4.SetTrustStoreArn(*r.ko.Spec.MutualAuthentication.TrustStoreARN)
		}
		res.SetMutualAuthentication(f4)
	}
	if r.ko.Spec.Port != nil {
		res.SetPort(*r.ko.Spec.Port)
	}
	if r.ko.Spec.Protocol != nil {
		res.SetProtocol(*r.ko.Spec.Protocol)
	}
	if r.ko.Spec.SSLPolicy != nil {
		res.SetSslPolicy(*r.ko.Spec.SSLPolicy)
	}
	if r.ko.Spec.Tags != nil {
		f8 := []*svcsdk.Tag{}
		for _, f8iter := range r.ko.Spec.Tags {
			f8elem := &svcsdk.Tag{}
			if f8iter.Key != nil {
				f8elem.SetKey(*f8iter.Key)
			}
			if f8iter.Value != nil {
				f8elem.SetValue(*f8iter.Value)
			}
			f8 = append(f8, f8elem)
		}
		res.SetTags(f8)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyListenerOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyListenerWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyListener", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			f0 := []*string{}
			for _, f0iter := range elem.AlpnPolicy {
				var f0elem string
				f0elem = *f0iter
				f0 = append(f0, &f0elem)
			}
			ko.Spec.AlpnPolicy = f0
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0f0 := map[string]*string{}
						for f2elemf0f0key, f2elemf0f0valiter := range f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams {
							var f2elemf0f0val string
							f2elemf0f0val = *f2elemf0f0valiter
							f2elemf0f0[f2elemf0f0key] = &f2elemf0f0val
						}
						f2elemf0.AuthenticationRequestExtraParams = f2elemf0f0
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
						f2elemf0.OnUnauthenticatedRequest = f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1f0 := map[string]*string{}
						for f2elemf1f0key, f2elemf1f0valiter := range f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams {
							var f2elemf1f0val string
							f2elemf1f0val = *f2elemf1f0valiter
							f2elemf1f0[f2elemf1f0key] = &f2elemf1f0val
						}
						f2elemf1.AuthenticationRequestExtraParams = f2elemf1f0
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != nil {
						f2elemf1.OnUnauthenticatedRequest = f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							f2elemf3f0.DurationSeconds = f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								f2elemf3f1elem.Weight = f2elemf3f1iter.Weight
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					f2elem.Order = f2iter.Order
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != nil {
						f2elemf5.StatusCode = f2iter.RedirectConfig.StatusCode
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != nil {
					f2elem.Type = f2iter.Type
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			ko.Spec.Port = elem.Port
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != nil {
			ko.Spec.Protocol = elem.Protocol
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyListenerInput, error) {
	res := &svcsdk.ModifyListenerInput{}

	if r.ko.Spec.AlpnPolicy != nil {
		f0 := []*string{}
		for _, f0iter := range r.ko.Spec.AlpnPolicy {
			var f0elem string
			f0elem = *f0iter
			f0 = append(f0, &f0elem)
		}
		res.SetAlpnPolicy(f0)
	}
	if r.ko.Spec.Certificates != nil {
		f1 := []*svcsdk.Certificate{}
		for _, f1iter := range r.ko.Spec.Certificates {
			f1elem := &svcsdk.Certificate{}
			if f1iter.CertificateARN != nil {
				f1elem.SetCertificateArn(*f1iter.CertificateARN)
			}
			if f1iter.IsDefault != nil {
				f1elem.SetIsDefault(*f1iter.IsDefault)
			}
			f1 = append(f1, f1elem)
		}
		res.SetCertificates(f1)
	}
	if r.ko.Spec.DefaultActions != nil {
		f2 := []*svcsdk.Action{}
		for _, f2iter := range r.ko.Spec.DefaultActions {
			f2elem := &svcsdk.Action{}
			if f2iter.AuthenticateCognitoConfig != nil {
				f2elemf0 := &svcsdk.AuthenticateCognitoActionConfig{}
				if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
					f2elemf0f0 := map[string]*string{}
					for f2elemf0f0key, f2elemf0f0valiter := range f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams {
						var f2elemf0f0val string
						f2elemf0f0val = *f2elemf0f0valiter
						f2elemf0f0[f2elemf0f0key] = &f2elemf0f0val
					}
					f2elemf0.SetAuthenticationRequestExtraParams(f2elemf0f0)
				}
				if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
					f2elemf0.SetOnUnauthenticatedRequest(*f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateCognitoConfig.Scope != nil {
					f2elemf0.SetScope(*f2iter.AuthenticateCognitoConfig.Scope)
				}
				if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
					f2elemf0.SetSessionCookieName(*f2iter.AuthenticateCognitoConfig.SessionCookieName)
				}
				if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
					f2elemf0.SetSessionTimeout(*f2iter.AuthenticateCognitoConfig.SessionTimeout)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolARN != nil {
					f2elemf0.SetUserPoolArn(*f2iter.AuthenticateCognitoConfig.UserPoolARN)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolClientID != nil {
					f2elemf0.SetUserPoolClientId(*f2iter.AuthenticateCognitoConfig.UserPoolClientID)
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
					f2elemf0.SetUserPoolDomain(*f2iter.AuthenticateCognitoConfig.UserPoolDomain)
				}
				f2elem.SetAuthenticateCognitoConfig(f2elemf0)
			}
			if f2iter.AuthenticateOIDCConfig != nil {
				f2elemf1 := &svcsdk.AuthenticateOidcActionConfig{}
				if f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams != nil {
					f2elemf1f0 := map[string]*string{}
					for f2elemf1f0key, f2elemf1f0valiter := range f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams {
						var f2elemf1f0val string
						f2elemf1f0val = *f2elemf1f0valiter
						f2elemf1f0[f2elemf1f0key] = &f2elemf1f0val
					}
					f2elemf1.SetAuthenticationRequestExtraParams(f2elemf1f0)
				}
				if f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint != nil {
					f2elemf1.SetAuthorizationEndpoint(*f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint)
				}
				if f2iter.AuthenticateOIDCConfig.ClientID != nil {
					f2elemf1.SetClientId(*f2iter.AuthenticateOIDCConfig.ClientID)
				}
				if f2iter.AuthenticateOIDCConfig.ClientSecret != nil {
					f2elemf1.SetClientSecret(*f2iter.AuthenticateOIDCConfig.ClientSecret)
				}
				if f2iter.AuthenticateOIDCConfig.Issuer != nil {
					f2elemf1.SetIssuer(*f2iter.AuthenticateOIDCConfig.Issuer)
				}
				if f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest != nil {
					f2elemf1.SetOnUnauthenticatedRequest(*f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateOIDCConfig.Scope != nil {
					f2elemf1.SetScope(*f2iter.AuthenticateOIDCConfig.Scope)
				}
				if f2iter.AuthenticateOIDCConfig.SessionCookieName != nil {
					f2elemf1.SetSessionCookieName(*f2iter.AuthenticateOIDCConfig.SessionCookieName)
				}
				if f2iter.AuthenticateOIDCConfig.SessionTimeout != nil {
					f2elemf1.SetSessionTimeout(*f2iter.AuthenticateOIDCConfig.SessionTimeout)
				}
				if f2iter.AuthenticateOIDCConfig.TokenEndpoint != nil {
					f2elemf1.SetTokenEndpoint(*f2iter.AuthenticateOIDCConfig.TokenEndpoint)
				}
				if f2iter.AuthenticateOIDCConfig.UseExistingClientSecret != nil {
					f2elemf1.SetUseExistingClientSecret(*f2iter.AuthenticateOIDCConfig.UseExistingClientSecret)
				}
				if f2iter.AuthenticateOIDCConfig.UserInfoEndpoint != nil {
					f2elemf1.SetUserInfoEndpoint(*f2iter.AuthenticateOIDCConfig.UserInfoEndpoint)
				}
				f2elem.SetAuthenticateOidcConfig(f2elemf1)
			}
			if f2iter.FixedResponseConfig != nil {
				f2elemf2 := &svcsdk.FixedResponseActionConfig{}
				if f2iter.FixedResponseConfig.ContentType != nil {
					f2elemf2.SetContentType(*f2iter.FixedResponseConfig.ContentType)
				}
				if f2iter.FixedResponseConfig.MessageBody != nil {
					f2elemf2.SetMessageBody(*f2iter.FixedResponseConfig.MessageBody)
				}
				if f2iter.FixedResponseConfig.StatusCode != nil {
					f2elemf2.SetStatusCode(*f2iter.FixedResponseConfig.StatusCode)
				}
				f2elem.SetFixedResponseConfig(f2elemf2)
			}
			if f2iter.ForwardConfig != nil {
				f2elemf3 := &svcsdk.ForwardActionConfig{}
				if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
					f2elemf3f0 := &svcsdk.TargetGroupStickinessConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
						f2elemf3f0.SetDurationSeconds(*f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds)
					}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
						f2elemf3f0.SetEnabled(*f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled)
					}
					f2elemf3.SetTargetGroupStickinessConfig(f2elemf3f0)
				}
				if f2iter.ForwardConfig.TargetGroups != nil {
					f2elemf3f1 := []*svcsdk.TargetGroupTuple{}
					for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
						f2elemf3f1elem := &svcsdk.TargetGroupTuple{}
						if f2elemf3f1iter.TargetGroupARN != nil {
							f2elemf3f1elem.SetTargetGroupArn(*f2elemf3f1iter.TargetGroupARN)
						}
						if f2elemf3f1iter.Weight != nil {
							f2elemf3f1elem.SetWeight(*f2elemf3f1iter.Weight)
						}
						f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
					}
					f2elemf3.SetTargetGroups(f2elemf3f1)
				}
				f2elem.SetForwardConfig(f2elemf3)
			}
			if f2iter.Order != nil {
				f2elem.SetOrder(*f2iter.Order)
			}
			if f2iter.RedirectConfig != nil {
				f2elemf5 := &svcsdk.RedirectActionConfig{}
				if f2iter.RedirectConfig.Host != nil {
					f2elemf5.SetHost(*f2iter.RedirectConfig.Host)
				}
				if f2iter.RedirectConfig.Path != nil {
					f2elemf5.SetPath(*f2iter.RedirectConfig.Path)
				}
				if f2iter.RedirectConfig.Port != nil {
					f2elemf5.SetPort(*f2iter.RedirectConfig.Port)
				}
				if f2iter.RedirectConfig.Protocol != nil {
					f2elemf5.SetProtocol(*f2iter.RedirectConfig.Protocol)
				}
				if f2iter.RedirectConfig.Query != nil {
					f2elemf5.SetQuery(*f2iter.RedirectConfig.Query)
				}
				if f2iter.RedirectConfig.StatusCode != nil {
					f2elemf5.SetStatusCode(*f2iter.RedirectConfig.StatusCode)
				}
				f2elem.SetRedirectConfig(f2elemf5)
			}
			if f2iter.TargetGroupARN != nil {
				f2elem.SetTargetGroupArn(*f2iter.TargetGroupARN)
			}
			if f2iter.Type != nil {
				f2elem.SetType(*f2iter.Type)
			}
			f2 = append(f2, f2elem)
		}
		res.SetDefaultActions(f2)
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.SetListenerArn(string(*r.ko.Status.ACKResourceMetadata.ARN))
	}
	if r.ko.Spec.MutualAuthentication != nil {
		f4 := &svcsdk.MutualAuthenticationAttributes{}
		if r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
			f4.SetIgnoreClientCertificateExpiry(*r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry)
		}
		if r.ko.Spec.MutualAuthentication.Mode != nil {
			f4.SetMode(*r.ko.Spec.MutualAuthentication.Mode)
		}
		if r.ko.Spec.MutualAuthentication.TrustStoreARN != nil {
			f4.SetTrustStoreArn(*r.ko.Spec.MutualAuthentication.TrustStoreARN)
		}
		res.SetMutualAuthentication(f4)
	}
	if r.ko.Spec.Port != nil {
		res.SetPort(*r.ko.Spec.Port)
	}
	if r.ko.Spec.Protocol != nil {
		res.SetProtocol(*r.ko.Spec.Protocol)
	}
	if r.ko.Spec.SSLPolicy != nil {
		res.SetSslPolicy(*r.ko.Spec.SSLPolicy)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteListenerOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteListenerWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteListener", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteListenerInput, error) {
	res := &svcsdk.DeleteListenerInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.SetListenerArn(string(*r.ko.Status.ACKResourceMetadata.ARN))
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Listener,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "ValidationError",
		"ALPNPolicyNotFound",
		"DuplicateListener",
		"IncompatibleProtocols",
		"InvalidConfigurationRequest",
		"InvalidLoadBalancerAction",
		"SSLPolicyNotFound",
		"UnsupportedProtocol",
		"InvalidParameter":
		return true
	default:
		return false
	}
}
