// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package listener

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elbv2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Listener{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// The ARN is guaranteed to be checked by the sdkFind method. We can safely cast it here.
	input.ListenerArns = []string{(string)(*r.ko.Status.ACKResourceMetadata.ARN)}
	// Unset the LoadBalancerArn field since we can't set both ListenerArn and LoadBalancerArn
	// Probably needs to be done in the code-generator. @a-hilaly.
	input.LoadBalancerArn = nil
	var resp *svcsdk.DescribeListenersOutput
	resp, err = rm.sdkapi.DescribeListeners(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeListeners", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ListenerNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			ko.Spec.AlpnPolicy = aws.StringSlice(elem.AlpnPolicy)
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != "" {
						f2elemf0.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != "" {
						f2elemf1.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							durationSecondsCopy := int64(*f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds)
							f2elemf3f0.DurationSeconds = &durationSecondsCopy
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								weightCopy := int64(*f2elemf3f1iter.Weight)
								f2elemf3f1elem.Weight = &weightCopy
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					orderCopy := int64(*f2iter.Order)
					f2elem.Order = &orderCopy
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != "" {
						f2elemf5.StatusCode = aws.String(string(f2iter.RedirectConfig.StatusCode))
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != "" {
					f2elem.Type = aws.String(string(f2iter.Type))
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			portCopy := int64(*elem.Port)
			ko.Spec.Port = &portCopy
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != "" {
			ko.Spec.Protocol = aws.String(string(elem.Protocol))
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return rm.customCheckRequiredFieldsMissingMethod(r)
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeListenersInput, error) {
	res := &svcsdk.DescribeListenersInput{}

	if r.ko.Spec.LoadBalancerARN != nil {
		res.LoadBalancerArn = r.ko.Spec.LoadBalancerARN
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateListenerOutput
	_ = resp
	resp, err = rm.sdkapi.CreateListener(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateListener", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			ko.Spec.AlpnPolicy = aws.StringSlice(elem.AlpnPolicy)
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != "" {
						f2elemf0.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != "" {
						f2elemf1.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							durationSecondsCopy := int64(*f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds)
							f2elemf3f0.DurationSeconds = &durationSecondsCopy
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								weightCopy := int64(*f2elemf3f1iter.Weight)
								f2elemf3f1elem.Weight = &weightCopy
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					orderCopy := int64(*f2iter.Order)
					f2elem.Order = &orderCopy
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != "" {
						f2elemf5.StatusCode = aws.String(string(f2iter.RedirectConfig.StatusCode))
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != "" {
					f2elem.Type = aws.String(string(f2iter.Type))
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			portCopy := int64(*elem.Port)
			ko.Spec.Port = &portCopy
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != "" {
			ko.Spec.Protocol = aws.String(string(elem.Protocol))
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateListenerInput, error) {
	res := &svcsdk.CreateListenerInput{}

	if r.ko.Spec.AlpnPolicy != nil {
		res.AlpnPolicy = aws.ToStringSlice(r.ko.Spec.AlpnPolicy)
	}
	if r.ko.Spec.Certificates != nil {
		f1 := []svcsdktypes.Certificate{}
		for _, f1iter := range r.ko.Spec.Certificates {
			f1elem := &svcsdktypes.Certificate{}
			if f1iter.CertificateARN != nil {
				f1elem.CertificateArn = f1iter.CertificateARN
			}
			if f1iter.IsDefault != nil {
				f1elem.IsDefault = f1iter.IsDefault
			}
			f1 = append(f1, *f1elem)
		}
		res.Certificates = f1
	}
	if r.ko.Spec.DefaultActions != nil {
		f2 := []svcsdktypes.Action{}
		for _, f2iter := range r.ko.Spec.DefaultActions {
			f2elem := &svcsdktypes.Action{}
			if f2iter.AuthenticateCognitoConfig != nil {
				f2elemf0 := &svcsdktypes.AuthenticateCognitoActionConfig{}
				if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
					f2elemf0.AuthenticationRequestExtraParams = aws.ToStringMap(f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams)
				}
				if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
					f2elemf0.OnUnauthenticatedRequest = svcsdktypes.AuthenticateCognitoActionConditionalBehaviorEnum(*f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateCognitoConfig.Scope != nil {
					f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
				}
				if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
					f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
				}
				if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
					f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolARN != nil {
					f2elemf0.UserPoolArn = f2iter.AuthenticateCognitoConfig.UserPoolARN
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolClientID != nil {
					f2elemf0.UserPoolClientId = f2iter.AuthenticateCognitoConfig.UserPoolClientID
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
					f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
				}
				f2elem.AuthenticateCognitoConfig = f2elemf0
			}
			if f2iter.AuthenticateOIDCConfig != nil {
				f2elemf1 := &svcsdktypes.AuthenticateOidcActionConfig{}
				if f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams != nil {
					f2elemf1.AuthenticationRequestExtraParams = aws.ToStringMap(f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams)
				}
				if f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint != nil {
					f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint
				}
				if f2iter.AuthenticateOIDCConfig.ClientID != nil {
					f2elemf1.ClientId = f2iter.AuthenticateOIDCConfig.ClientID
				}
				if f2iter.AuthenticateOIDCConfig.ClientSecret != nil {
					f2elemf1.ClientSecret = f2iter.AuthenticateOIDCConfig.ClientSecret
				}
				if f2iter.AuthenticateOIDCConfig.Issuer != nil {
					f2elemf1.Issuer = f2iter.AuthenticateOIDCConfig.Issuer
				}
				if f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest != nil {
					f2elemf1.OnUnauthenticatedRequest = svcsdktypes.AuthenticateOidcActionConditionalBehaviorEnum(*f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateOIDCConfig.Scope != nil {
					f2elemf1.Scope = f2iter.AuthenticateOIDCConfig.Scope
				}
				if f2iter.AuthenticateOIDCConfig.SessionCookieName != nil {
					f2elemf1.SessionCookieName = f2iter.AuthenticateOIDCConfig.SessionCookieName
				}
				if f2iter.AuthenticateOIDCConfig.SessionTimeout != nil {
					f2elemf1.SessionTimeout = f2iter.AuthenticateOIDCConfig.SessionTimeout
				}
				if f2iter.AuthenticateOIDCConfig.TokenEndpoint != nil {
					f2elemf1.TokenEndpoint = f2iter.AuthenticateOIDCConfig.TokenEndpoint
				}
				if f2iter.AuthenticateOIDCConfig.UseExistingClientSecret != nil {
					f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOIDCConfig.UseExistingClientSecret
				}
				if f2iter.AuthenticateOIDCConfig.UserInfoEndpoint != nil {
					f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOIDCConfig.UserInfoEndpoint
				}
				f2elem.AuthenticateOidcConfig = f2elemf1
			}
			if f2iter.FixedResponseConfig != nil {
				f2elemf2 := &svcsdktypes.FixedResponseActionConfig{}
				if f2iter.FixedResponseConfig.ContentType != nil {
					f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
				}
				if f2iter.FixedResponseConfig.MessageBody != nil {
					f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
				}
				if f2iter.FixedResponseConfig.StatusCode != nil {
					f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
				}
				f2elem.FixedResponseConfig = f2elemf2
			}
			if f2iter.ForwardConfig != nil {
				f2elemf3 := &svcsdktypes.ForwardActionConfig{}
				if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
					f2elemf3f0 := &svcsdktypes.TargetGroupStickinessConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
						durationSecondsCopy0 := *f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds
						if durationSecondsCopy0 > math.MaxInt32 || durationSecondsCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field DurationSeconds is of type int32")
						}
						durationSecondsCopy := int32(durationSecondsCopy0)
						f2elemf3f0.DurationSeconds = &durationSecondsCopy
					}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
						f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
					}
					f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
				}
				if f2iter.ForwardConfig.TargetGroups != nil {
					f2elemf3f1 := []svcsdktypes.TargetGroupTuple{}
					for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
						f2elemf3f1elem := &svcsdktypes.TargetGroupTuple{}
						if f2elemf3f1iter.TargetGroupARN != nil {
							f2elemf3f1elem.TargetGroupArn = f2elemf3f1iter.TargetGroupARN
						}
						if f2elemf3f1iter.Weight != nil {
							weightCopy0 := *f2elemf3f1iter.Weight
							if weightCopy0 > math.MaxInt32 || weightCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field Weight is of type int32")
							}
							weightCopy := int32(weightCopy0)
							f2elemf3f1elem.Weight = &weightCopy
						}
						f2elemf3f1 = append(f2elemf3f1, *f2elemf3f1elem)
					}
					f2elemf3.TargetGroups = f2elemf3f1
				}
				f2elem.ForwardConfig = f2elemf3
			}
			if f2iter.Order != nil {
				orderCopy0 := *f2iter.Order
				if orderCopy0 > math.MaxInt32 || orderCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field Order is of type int32")
				}
				orderCopy := int32(orderCopy0)
				f2elem.Order = &orderCopy
			}
			if f2iter.RedirectConfig != nil {
				f2elemf5 := &svcsdktypes.RedirectActionConfig{}
				if f2iter.RedirectConfig.Host != nil {
					f2elemf5.Host = f2iter.RedirectConfig.Host
				}
				if f2iter.RedirectConfig.Path != nil {
					f2elemf5.Path = f2iter.RedirectConfig.Path
				}
				if f2iter.RedirectConfig.Port != nil {
					f2elemf5.Port = f2iter.RedirectConfig.Port
				}
				if f2iter.RedirectConfig.Protocol != nil {
					f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
				}
				if f2iter.RedirectConfig.Query != nil {
					f2elemf5.Query = f2iter.RedirectConfig.Query
				}
				if f2iter.RedirectConfig.StatusCode != nil {
					f2elemf5.StatusCode = svcsdktypes.RedirectActionStatusCodeEnum(*f2iter.RedirectConfig.StatusCode)
				}
				f2elem.RedirectConfig = f2elemf5
			}
			if f2iter.TargetGroupARN != nil {
				f2elem.TargetGroupArn = f2iter.TargetGroupARN
			}
			if f2iter.Type != nil {
				f2elem.Type = svcsdktypes.ActionTypeEnum(*f2iter.Type)
			}
			f2 = append(f2, *f2elem)
		}
		res.DefaultActions = f2
	}
	if r.ko.Spec.LoadBalancerARN != nil {
		res.LoadBalancerArn = r.ko.Spec.LoadBalancerARN
	}
	if r.ko.Spec.MutualAuthentication != nil {
		f4 := &svcsdktypes.MutualAuthenticationAttributes{}
		if r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
			f4.IgnoreClientCertificateExpiry = r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry
		}
		if r.ko.Spec.MutualAuthentication.Mode != nil {
			f4.Mode = r.ko.Spec.MutualAuthentication.Mode
		}
		if r.ko.Spec.MutualAuthentication.TrustStoreARN != nil {
			f4.TrustStoreArn = r.ko.Spec.MutualAuthentication.TrustStoreARN
		}
		res.MutualAuthentication = f4
	}
	if r.ko.Spec.Port != nil {
		portCopy0 := *r.ko.Spec.Port
		if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Port is of type int32")
		}
		portCopy := int32(portCopy0)
		res.Port = &portCopy
	}
	if r.ko.Spec.Protocol != nil {
		res.Protocol = svcsdktypes.ProtocolEnum(*r.ko.Spec.Protocol)
	}
	if r.ko.Spec.SSLPolicy != nil {
		res.SslPolicy = r.ko.Spec.SSLPolicy
	}
	if r.ko.Spec.Tags != nil {
		f8 := []svcsdktypes.Tag{}
		for _, f8iter := range r.ko.Spec.Tags {
			f8elem := &svcsdktypes.Tag{}
			if f8iter.Key != nil {
				f8elem.Key = f8iter.Key
			}
			if f8iter.Value != nil {
				f8elem.Value = f8iter.Value
			}
			f8 = append(f8, *f8elem)
		}
		res.Tags = f8
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyListenerOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyListener(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyListener", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	found := false
	for _, elem := range resp.Listeners {
		if elem.AlpnPolicy != nil {
			ko.Spec.AlpnPolicy = aws.StringSlice(elem.AlpnPolicy)
		} else {
			ko.Spec.AlpnPolicy = nil
		}
		if elem.Certificates != nil {
			f1 := []*svcapitypes.Certificate{}
			for _, f1iter := range elem.Certificates {
				f1elem := &svcapitypes.Certificate{}
				if f1iter.CertificateArn != nil {
					f1elem.CertificateARN = f1iter.CertificateArn
				}
				if f1iter.IsDefault != nil {
					f1elem.IsDefault = f1iter.IsDefault
				}
				f1 = append(f1, f1elem)
			}
			ko.Spec.Certificates = f1
		} else {
			ko.Spec.Certificates = nil
		}
		if elem.DefaultActions != nil {
			f2 := []*svcapitypes.Action{}
			for _, f2iter := range elem.DefaultActions {
				f2elem := &svcapitypes.Action{}
				if f2iter.AuthenticateCognitoConfig != nil {
					f2elemf0 := &svcapitypes.AuthenticateCognitoActionConfig{}
					if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
						f2elemf0.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != "" {
						f2elemf0.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateCognitoConfig.Scope != nil {
						f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
					}
					if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
						f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
					}
					if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
						f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolArn != nil {
						f2elemf0.UserPoolARN = f2iter.AuthenticateCognitoConfig.UserPoolArn
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolClientId != nil {
						f2elemf0.UserPoolClientID = f2iter.AuthenticateCognitoConfig.UserPoolClientId
					}
					if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
						f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
					}
					f2elem.AuthenticateCognitoConfig = f2elemf0
				}
				if f2iter.AuthenticateOidcConfig != nil {
					f2elemf1 := &svcapitypes.AuthenticateOIDCActionConfig{}
					if f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams != nil {
						f2elemf1.AuthenticationRequestExtraParams = aws.StringMap(f2iter.AuthenticateOidcConfig.AuthenticationRequestExtraParams)
					}
					if f2iter.AuthenticateOidcConfig.AuthorizationEndpoint != nil {
						f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOidcConfig.AuthorizationEndpoint
					}
					if f2iter.AuthenticateOidcConfig.ClientId != nil {
						f2elemf1.ClientID = f2iter.AuthenticateOidcConfig.ClientId
					}
					if f2iter.AuthenticateOidcConfig.ClientSecret != nil {
						f2elemf1.ClientSecret = f2iter.AuthenticateOidcConfig.ClientSecret
					}
					if f2iter.AuthenticateOidcConfig.Issuer != nil {
						f2elemf1.Issuer = f2iter.AuthenticateOidcConfig.Issuer
					}
					if f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest != "" {
						f2elemf1.OnUnauthenticatedRequest = aws.String(string(f2iter.AuthenticateOidcConfig.OnUnauthenticatedRequest))
					}
					if f2iter.AuthenticateOidcConfig.Scope != nil {
						f2elemf1.Scope = f2iter.AuthenticateOidcConfig.Scope
					}
					if f2iter.AuthenticateOidcConfig.SessionCookieName != nil {
						f2elemf1.SessionCookieName = f2iter.AuthenticateOidcConfig.SessionCookieName
					}
					if f2iter.AuthenticateOidcConfig.SessionTimeout != nil {
						f2elemf1.SessionTimeout = f2iter.AuthenticateOidcConfig.SessionTimeout
					}
					if f2iter.AuthenticateOidcConfig.TokenEndpoint != nil {
						f2elemf1.TokenEndpoint = f2iter.AuthenticateOidcConfig.TokenEndpoint
					}
					if f2iter.AuthenticateOidcConfig.UseExistingClientSecret != nil {
						f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOidcConfig.UseExistingClientSecret
					}
					if f2iter.AuthenticateOidcConfig.UserInfoEndpoint != nil {
						f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOidcConfig.UserInfoEndpoint
					}
					f2elem.AuthenticateOIDCConfig = f2elemf1
				}
				if f2iter.FixedResponseConfig != nil {
					f2elemf2 := &svcapitypes.FixedResponseActionConfig{}
					if f2iter.FixedResponseConfig.ContentType != nil {
						f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
					}
					if f2iter.FixedResponseConfig.MessageBody != nil {
						f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
					}
					if f2iter.FixedResponseConfig.StatusCode != nil {
						f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
					}
					f2elem.FixedResponseConfig = f2elemf2
				}
				if f2iter.ForwardConfig != nil {
					f2elemf3 := &svcapitypes.ForwardActionConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
						f2elemf3f0 := &svcapitypes.TargetGroupStickinessConfig{}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
							durationSecondsCopy := int64(*f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds)
							f2elemf3f0.DurationSeconds = &durationSecondsCopy
						}
						if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
							f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
						}
						f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
					}
					if f2iter.ForwardConfig.TargetGroups != nil {
						f2elemf3f1 := []*svcapitypes.TargetGroupTuple{}
						for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
							f2elemf3f1elem := &svcapitypes.TargetGroupTuple{}
							if f2elemf3f1iter.TargetGroupArn != nil {
								f2elemf3f1elem.TargetGroupARN = f2elemf3f1iter.TargetGroupArn
							}
							if f2elemf3f1iter.Weight != nil {
								weightCopy := int64(*f2elemf3f1iter.Weight)
								f2elemf3f1elem.Weight = &weightCopy
							}
							f2elemf3f1 = append(f2elemf3f1, f2elemf3f1elem)
						}
						f2elemf3.TargetGroups = f2elemf3f1
					}
					f2elem.ForwardConfig = f2elemf3
				}
				if f2iter.Order != nil {
					orderCopy := int64(*f2iter.Order)
					f2elem.Order = &orderCopy
				}
				if f2iter.RedirectConfig != nil {
					f2elemf5 := &svcapitypes.RedirectActionConfig{}
					if f2iter.RedirectConfig.Host != nil {
						f2elemf5.Host = f2iter.RedirectConfig.Host
					}
					if f2iter.RedirectConfig.Path != nil {
						f2elemf5.Path = f2iter.RedirectConfig.Path
					}
					if f2iter.RedirectConfig.Port != nil {
						f2elemf5.Port = f2iter.RedirectConfig.Port
					}
					if f2iter.RedirectConfig.Protocol != nil {
						f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
					}
					if f2iter.RedirectConfig.Query != nil {
						f2elemf5.Query = f2iter.RedirectConfig.Query
					}
					if f2iter.RedirectConfig.StatusCode != "" {
						f2elemf5.StatusCode = aws.String(string(f2iter.RedirectConfig.StatusCode))
					}
					f2elem.RedirectConfig = f2elemf5
				}
				if f2iter.TargetGroupArn != nil {
					f2elem.TargetGroupARN = f2iter.TargetGroupArn
				}
				if f2iter.Type != "" {
					f2elem.Type = aws.String(string(f2iter.Type))
				}
				f2 = append(f2, f2elem)
			}
			ko.Spec.DefaultActions = f2
		} else {
			ko.Spec.DefaultActions = nil
		}
		if elem.ListenerArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ListenerArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.LoadBalancerArn != nil {
			ko.Spec.LoadBalancerARN = elem.LoadBalancerArn
		} else {
			ko.Spec.LoadBalancerARN = nil
		}
		if elem.MutualAuthentication != nil {
			f5 := &svcapitypes.MutualAuthenticationAttributes{}
			if elem.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
				f5.IgnoreClientCertificateExpiry = elem.MutualAuthentication.IgnoreClientCertificateExpiry
			}
			if elem.MutualAuthentication.Mode != nil {
				f5.Mode = elem.MutualAuthentication.Mode
			}
			if elem.MutualAuthentication.TrustStoreArn != nil {
				f5.TrustStoreARN = elem.MutualAuthentication.TrustStoreArn
			}
			ko.Spec.MutualAuthentication = f5
		} else {
			ko.Spec.MutualAuthentication = nil
		}
		if elem.Port != nil {
			portCopy := int64(*elem.Port)
			ko.Spec.Port = &portCopy
		} else {
			ko.Spec.Port = nil
		}
		if elem.Protocol != "" {
			ko.Spec.Protocol = aws.String(string(elem.Protocol))
		} else {
			ko.Spec.Protocol = nil
		}
		if elem.SslPolicy != nil {
			ko.Spec.SSLPolicy = elem.SslPolicy
		} else {
			ko.Spec.SSLPolicy = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyListenerInput, error) {
	res := &svcsdk.ModifyListenerInput{}

	if r.ko.Spec.AlpnPolicy != nil {
		res.AlpnPolicy = aws.ToStringSlice(r.ko.Spec.AlpnPolicy)
	}
	if r.ko.Spec.Certificates != nil {
		f1 := []svcsdktypes.Certificate{}
		for _, f1iter := range r.ko.Spec.Certificates {
			f1elem := &svcsdktypes.Certificate{}
			if f1iter.CertificateARN != nil {
				f1elem.CertificateArn = f1iter.CertificateARN
			}
			if f1iter.IsDefault != nil {
				f1elem.IsDefault = f1iter.IsDefault
			}
			f1 = append(f1, *f1elem)
		}
		res.Certificates = f1
	}
	if r.ko.Spec.DefaultActions != nil {
		f2 := []svcsdktypes.Action{}
		for _, f2iter := range r.ko.Spec.DefaultActions {
			f2elem := &svcsdktypes.Action{}
			if f2iter.AuthenticateCognitoConfig != nil {
				f2elemf0 := &svcsdktypes.AuthenticateCognitoActionConfig{}
				if f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams != nil {
					f2elemf0.AuthenticationRequestExtraParams = aws.ToStringMap(f2iter.AuthenticateCognitoConfig.AuthenticationRequestExtraParams)
				}
				if f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest != nil {
					f2elemf0.OnUnauthenticatedRequest = svcsdktypes.AuthenticateCognitoActionConditionalBehaviorEnum(*f2iter.AuthenticateCognitoConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateCognitoConfig.Scope != nil {
					f2elemf0.Scope = f2iter.AuthenticateCognitoConfig.Scope
				}
				if f2iter.AuthenticateCognitoConfig.SessionCookieName != nil {
					f2elemf0.SessionCookieName = f2iter.AuthenticateCognitoConfig.SessionCookieName
				}
				if f2iter.AuthenticateCognitoConfig.SessionTimeout != nil {
					f2elemf0.SessionTimeout = f2iter.AuthenticateCognitoConfig.SessionTimeout
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolARN != nil {
					f2elemf0.UserPoolArn = f2iter.AuthenticateCognitoConfig.UserPoolARN
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolClientID != nil {
					f2elemf0.UserPoolClientId = f2iter.AuthenticateCognitoConfig.UserPoolClientID
				}
				if f2iter.AuthenticateCognitoConfig.UserPoolDomain != nil {
					f2elemf0.UserPoolDomain = f2iter.AuthenticateCognitoConfig.UserPoolDomain
				}
				f2elem.AuthenticateCognitoConfig = f2elemf0
			}
			if f2iter.AuthenticateOIDCConfig != nil {
				f2elemf1 := &svcsdktypes.AuthenticateOidcActionConfig{}
				if f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams != nil {
					f2elemf1.AuthenticationRequestExtraParams = aws.ToStringMap(f2iter.AuthenticateOIDCConfig.AuthenticationRequestExtraParams)
				}
				if f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint != nil {
					f2elemf1.AuthorizationEndpoint = f2iter.AuthenticateOIDCConfig.AuthorizationEndpoint
				}
				if f2iter.AuthenticateOIDCConfig.ClientID != nil {
					f2elemf1.ClientId = f2iter.AuthenticateOIDCConfig.ClientID
				}
				if f2iter.AuthenticateOIDCConfig.ClientSecret != nil {
					f2elemf1.ClientSecret = f2iter.AuthenticateOIDCConfig.ClientSecret
				}
				if f2iter.AuthenticateOIDCConfig.Issuer != nil {
					f2elemf1.Issuer = f2iter.AuthenticateOIDCConfig.Issuer
				}
				if f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest != nil {
					f2elemf1.OnUnauthenticatedRequest = svcsdktypes.AuthenticateOidcActionConditionalBehaviorEnum(*f2iter.AuthenticateOIDCConfig.OnUnauthenticatedRequest)
				}
				if f2iter.AuthenticateOIDCConfig.Scope != nil {
					f2elemf1.Scope = f2iter.AuthenticateOIDCConfig.Scope
				}
				if f2iter.AuthenticateOIDCConfig.SessionCookieName != nil {
					f2elemf1.SessionCookieName = f2iter.AuthenticateOIDCConfig.SessionCookieName
				}
				if f2iter.AuthenticateOIDCConfig.SessionTimeout != nil {
					f2elemf1.SessionTimeout = f2iter.AuthenticateOIDCConfig.SessionTimeout
				}
				if f2iter.AuthenticateOIDCConfig.TokenEndpoint != nil {
					f2elemf1.TokenEndpoint = f2iter.AuthenticateOIDCConfig.TokenEndpoint
				}
				if f2iter.AuthenticateOIDCConfig.UseExistingClientSecret != nil {
					f2elemf1.UseExistingClientSecret = f2iter.AuthenticateOIDCConfig.UseExistingClientSecret
				}
				if f2iter.AuthenticateOIDCConfig.UserInfoEndpoint != nil {
					f2elemf1.UserInfoEndpoint = f2iter.AuthenticateOIDCConfig.UserInfoEndpoint
				}
				f2elem.AuthenticateOidcConfig = f2elemf1
			}
			if f2iter.FixedResponseConfig != nil {
				f2elemf2 := &svcsdktypes.FixedResponseActionConfig{}
				if f2iter.FixedResponseConfig.ContentType != nil {
					f2elemf2.ContentType = f2iter.FixedResponseConfig.ContentType
				}
				if f2iter.FixedResponseConfig.MessageBody != nil {
					f2elemf2.MessageBody = f2iter.FixedResponseConfig.MessageBody
				}
				if f2iter.FixedResponseConfig.StatusCode != nil {
					f2elemf2.StatusCode = f2iter.FixedResponseConfig.StatusCode
				}
				f2elem.FixedResponseConfig = f2elemf2
			}
			if f2iter.ForwardConfig != nil {
				f2elemf3 := &svcsdktypes.ForwardActionConfig{}
				if f2iter.ForwardConfig.TargetGroupStickinessConfig != nil {
					f2elemf3f0 := &svcsdktypes.TargetGroupStickinessConfig{}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds != nil {
						durationSecondsCopy0 := *f2iter.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds
						if durationSecondsCopy0 > math.MaxInt32 || durationSecondsCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field DurationSeconds is of type int32")
						}
						durationSecondsCopy := int32(durationSecondsCopy0)
						f2elemf3f0.DurationSeconds = &durationSecondsCopy
					}
					if f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled != nil {
						f2elemf3f0.Enabled = f2iter.ForwardConfig.TargetGroupStickinessConfig.Enabled
					}
					f2elemf3.TargetGroupStickinessConfig = f2elemf3f0
				}
				if f2iter.ForwardConfig.TargetGroups != nil {
					f2elemf3f1 := []svcsdktypes.TargetGroupTuple{}
					for _, f2elemf3f1iter := range f2iter.ForwardConfig.TargetGroups {
						f2elemf3f1elem := &svcsdktypes.TargetGroupTuple{}
						if f2elemf3f1iter.TargetGroupARN != nil {
							f2elemf3f1elem.TargetGroupArn = f2elemf3f1iter.TargetGroupARN
						}
						if f2elemf3f1iter.Weight != nil {
							weightCopy0 := *f2elemf3f1iter.Weight
							if weightCopy0 > math.MaxInt32 || weightCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field Weight is of type int32")
							}
							weightCopy := int32(weightCopy0)
							f2elemf3f1elem.Weight = &weightCopy
						}
						f2elemf3f1 = append(f2elemf3f1, *f2elemf3f1elem)
					}
					f2elemf3.TargetGroups = f2elemf3f1
				}
				f2elem.ForwardConfig = f2elemf3
			}
			if f2iter.Order != nil {
				orderCopy0 := *f2iter.Order
				if orderCopy0 > math.MaxInt32 || orderCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field Order is of type int32")
				}
				orderCopy := int32(orderCopy0)
				f2elem.Order = &orderCopy
			}
			if f2iter.RedirectConfig != nil {
				f2elemf5 := &svcsdktypes.RedirectActionConfig{}
				if f2iter.RedirectConfig.Host != nil {
					f2elemf5.Host = f2iter.RedirectConfig.Host
				}
				if f2iter.RedirectConfig.Path != nil {
					f2elemf5.Path = f2iter.RedirectConfig.Path
				}
				if f2iter.RedirectConfig.Port != nil {
					f2elemf5.Port = f2iter.RedirectConfig.Port
				}
				if f2iter.RedirectConfig.Protocol != nil {
					f2elemf5.Protocol = f2iter.RedirectConfig.Protocol
				}
				if f2iter.RedirectConfig.Query != nil {
					f2elemf5.Query = f2iter.RedirectConfig.Query
				}
				if f2iter.RedirectConfig.StatusCode != nil {
					f2elemf5.StatusCode = svcsdktypes.RedirectActionStatusCodeEnum(*f2iter.RedirectConfig.StatusCode)
				}
				f2elem.RedirectConfig = f2elemf5
			}
			if f2iter.TargetGroupARN != nil {
				f2elem.TargetGroupArn = f2iter.TargetGroupARN
			}
			if f2iter.Type != nil {
				f2elem.Type = svcsdktypes.ActionTypeEnum(*f2iter.Type)
			}
			f2 = append(f2, *f2elem)
		}
		res.DefaultActions = f2
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ListenerArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.MutualAuthentication != nil {
		f4 := &svcsdktypes.MutualAuthenticationAttributes{}
		if r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry != nil {
			f4.IgnoreClientCertificateExpiry = r.ko.Spec.MutualAuthentication.IgnoreClientCertificateExpiry
		}
		if r.ko.Spec.MutualAuthentication.Mode != nil {
			f4.Mode = r.ko.Spec.MutualAuthentication.Mode
		}
		if r.ko.Spec.MutualAuthentication.TrustStoreARN != nil {
			f4.TrustStoreArn = r.ko.Spec.MutualAuthentication.TrustStoreARN
		}
		res.MutualAuthentication = f4
	}
	if r.ko.Spec.Port != nil {
		portCopy0 := *r.ko.Spec.Port
		if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Port is of type int32")
		}
		portCopy := int32(portCopy0)
		res.Port = &portCopy
	}
	if r.ko.Spec.Protocol != nil {
		res.Protocol = svcsdktypes.ProtocolEnum(*r.ko.Spec.Protocol)
	}
	if r.ko.Spec.SSLPolicy != nil {
		res.SslPolicy = r.ko.Spec.SSLPolicy
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteListenerOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteListener(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteListener", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteListenerInput, error) {
	res := &svcsdk.DeleteListenerInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ListenerArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Listener,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ALPNPolicyNotFound",
		"ValidationError",
		"DuplicateListener",
		"IncompatibleProtocols",
		"InvalidConfigurationRequest",
		"InvalidLoadBalancerAction",
		"SSLPolicyNotFound",
		"UnsupportedProtocol",
		"InvalidParameter":
		return true
	default:
		return false
	}
}
